'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BluegreenOnline

    Partial Public Class AccountNumberLookup

        '''<summary>
        '''enrollForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enrollForm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''imgAlert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAlert As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblErrorPersonal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorPersonal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEntry As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAcctSocial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcctSocial As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAcctPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcctPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''submitBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents submitBtn As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cancelBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cancelBtn As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''pnlResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlResult As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblAcctID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAcctID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnGoToEnroll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnGoToEnroll As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''footer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents footer As Global.BGO.BluegreenOnline.footer
    End Class
End Namespace
