'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BluegreenOnline

    Partial Public Class enroll

        '''<summary>
        '''enrollForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enrollForm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''imgAlert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAlert As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblErrorSignIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorSignIn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAcctNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcctNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAcctPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcctPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAcctSocial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcctSocial As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAcctEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcctEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAcctEmail2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcctEmail2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAcctPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcctPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAcctPassword2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcctPassword2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''enrollBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents enrollBtn As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cancelBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cancelBtn As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''footer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents footer As Global.BGO.BluegreenOnline.footer
    End Class
End Namespace
