'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BluegreenOnline

    Partial Public Class forgotPassword

        '''<summary>
        '''imgAlert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAlert As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblErrors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''forgotPasswordForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents forgotPasswordForm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''txtEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSSN As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgSubmit As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
