'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BluegreenOnline

    Partial Public Class HomeTP

        '''<summary>
        '''UcMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UcMenu1 As Global.BGO.BluegreenOnline.Migrated_ucMenu

        '''<summary>
        '''lNav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lNav As Global.BGO.TravelerPlus_includes_TPleftNav

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ImgBtnQuickSearchAir control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImgBtnQuickSearchAir As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ImgBtnQuickSearchCar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImgBtnQuickSearchCar As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ImgBtnQuickSearchHotel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImgBtnQuickSearchHotel As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''PnlAir control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PnlAir As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''PnlCar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PnlCar As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlHotel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHotel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Specials1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Specials1 As Global.BGO.BluegreenOnline.Specials

        '''<summary>
        '''Features1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Features1 As Global.BGO.BluegreenOnline.Features

        '''<summary>
        '''footer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents footer As Global.BGO.BluegreenOnline.footer
    End Class
End Namespace
