'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BluegreenOnline

    Partial Public Class TravelerPlus_owner_HotelPointStays

        '''<summary>
        '''Head1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''UcMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UcMenu1 As Global.BGO.BluegreenOnline.Migrated_ucMenu

        '''<summary>
        '''lNav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lNav As Global.BGO.BluegreenOnline.TravelerPlus.TravelerPlus_includes_TPleftNav

        '''<summary>
        '''BannerRotation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BannerRotation As Global.BGO.BluegreenOnline.TravelerPlus.bannerRotation

        '''<summary>
        '''footer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents footer As Global.BGO.BluegreenOnline.TravelerPlus.footerTP
    End Class
End Namespace
