'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BluegreenOnline

    Partial Public Class loginUnsuccessful

        '''<summary>
        '''OwnerLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OwnerLogin As Global.BGO.BluegreenOnline.OwnerLogin

        '''<summary>
        '''pnlNonSampler control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNonSampler As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlSampler control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSampler As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''PnlPlayer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PnlPlayer As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''PnlPono control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PnlPono As Global.System.Web.UI.WebControls.Panel
    End Class
End Namespace
