'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BluegreenOnline

    Partial Public Class payAcctBal

        '''<summary>
        '''UcMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UcMenu1 As Global.BGO.BluegreenOnline.Migrated_ucMenu

        '''<summary>
        '''OwnerPalette control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OwnerPalette As Global.BGO.BluegreenOnline.OwnerPalette

        '''<summary>
        '''MOLNav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MOLNav As Global.BGO.includes_mortgageonlinenav

        '''<summary>
        '''NewResorts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NewResorts As Global.BGO.BluegreenOnline.FeaturedResorts

        '''<summary>
        '''DynamicSpecials1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DynamicSpecials1 As Global.BGO.BluegreenOnline.dynamicSpecials

        '''<summary>
        '''PanelError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PanelError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlDoesNotQualify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDoesNotQualify As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlPaidinFull control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPaidinFull As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlInstallment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInstallment As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ltlInstallment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltlInstallment As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlPayments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPayments As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlPending control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPending As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlErrorAccessing500 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlErrorAccessing500 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''frmAcct50 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmAcct50 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''btnPrepayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPrepayment As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ValidationSummary1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''lblErrors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gvOUTER control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvOUTER As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''noOUterROws control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents noOUterROws As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlPayInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPayInfo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlARDA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlARDA As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''vegasPromo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vegasPromo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''footer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents footer As Global.BGO.BluegreenOnline.footer
    End Class
End Namespace
