'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BluegreenOnline

    Partial Public Class payConfirm

        '''<summary>
        '''UcMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UcMenu1 As Global.BGO.BluegreenOnline.Migrated_ucMenu

        '''<summary>
        '''OwnerPalette control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OwnerPalette As Global.BGO.BluegreenOnline.OwnerPalette

        '''<summary>
        '''NewResorts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NewResorts As Global.BGO.BluegreenOnline.FeaturedResorts

        '''<summary>
        '''DynamicSpecials1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DynamicSpecials1 As Global.BGO.BluegreenOnline.dynamicSpecials

        '''<summary>
        '''paperless control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents paperless As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''pnlCredit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCredit As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAmount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblConfirmation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConfirmation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlChecking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlChecking As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''achlblAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents achlblAmount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlPromotion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPromotion As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlPromotion_2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPromotion_2 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''footer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents footer As Global.BGO.BluegreenOnline.footer
    End Class
End Namespace
